### ISSUE TITLE
Issues with parsing hold-ends with certain note quants?

### ISSUE THREAD

**Issue by StarUndrscre** [oatmealine/trackmaker#2]
I'm writing a chart that has a lot of swing rhythms, and for some unknown reason, holds that start on a 12th or 24th note quant and end at the start of the next measure don't get their hold-ends saved correctly.

### Hold note that starts on a 12th and ends at the next measure:
![image](https://github.com/user-attachments/assets/1494144f-5509-4fe8-b0b1-eb9b1e3dcb17)

### The same hold note, this time ending a 12th of a beat earlier:
![image](https://github.com/user-attachments/assets/cb27ceb9-8ba9-48b2-bf6a-a8bfdefb5db9)

**Comment by oatmealine** [comment]
was a really annoying issue with `beat + length` ending up _nearly_ crossing the beat boundary, but not quite, resulting in it still counting as being in the previous beat. shoving in an epsilon in the `thing.beat >= b` seems to solve it with no Side Effects, so for now i'll consider it fixed as of 224dd89
![image](https://github.com/user-attachments/assets/e652788a-c43f-4537-86a4-e15213483203)
